// app/plugins/shifty-plugin/src/connections/Knex/requests/DeleteShiftSlot.js
// Lowdefy custom request: delete a shift_slot row, BLOCKED if any shift_instance
// references it (per CONTEXT D-Area-1: "Delete shift slot when instances already
// generated by an open window: block").
//
// Tenant ID from request.user (session) — NEVER from request.properties. Layer-4 defense.
// RESEARCH Risk R-03-2: every UPDATE/DELETE explicitly scopes on tenant_id even
// though RLS Layer 5 backstops.
//
// Implementation (Plan 03-03 Task 1):
// - Guards: tenant_id, actor_user_id, role guard.
// - Load existing slot (used for team_id scope check + audit pre-image).
// - Layer-4 manager scope check (membership-join).
// - EXISTS check against shift_instance — refuse if any reference exists.
//   The error message string 'shift_slot_has_instances' is the discriminator the
//   YAML toast keys on (Task 2 maps it to a Hebrew message).
// - DELETE WHERE id = :shift_slot_id AND tenant_id = :tenant_id.
// - schedule_audit (to_state='shift_slot_deleted'); written BEFORE the DELETE so
//   the audit row's payload captures the slot's pre-image (the same TX still
//   commits/rolls back atomically with the DELETE).

import { withTenantTx } from '../../../hooks/with-tenant-tx.js';

async function DeleteShiftSlot({ request, connection }) {
  const { shift_slot_id } = request.properties || {};

  // Layer-4 tenant / actor guards.
  const tenant_id = request.user?.tenant_id;
  if (!tenant_id) {
    throw new Error('DeleteShiftSlot: tenant_id missing from session');
  }
  const actor_user_id = request.user?.user_id;
  if (!actor_user_id) {
    throw new Error('DeleteShiftSlot: actor_user_id missing from session — unauthenticated request');
  }
  const roles = request.user?.roles || [];
  const is_admin = roles.includes('unit_admin');
  const is_manager = roles.includes('team_manager');
  if (!is_admin && !is_manager) {
    throw new Error('DeleteShiftSlot: requires unit_admin or team_manager role');
  }

  if (!shift_slot_id) {
    throw new Error('DeleteShiftSlot: shift_slot_id is required');
  }

  const result = await withTenantTx(connection, tenant_id, async (trx) => {
    // Load pre-image — defines team_id for scope check, payload for audit.
    const existing = await trx('shift_slot')
      .where({ id: shift_slot_id, tenant_id })
      .first();
    if (!existing) {
      throw new Error('DeleteShiftSlot: shift_slot not found in tenant');
    }

    // Layer-4 scope check.
    if (!is_admin) {
      const own = await trx('membership')
        .where({ tenant_id, org_unit_id: existing.team_id, role: 'team_manager' })
        .whereIn('soldier_id', function () {
          this.select('id').from('soldier').where({ tenant_id, user_id: actor_user_id });
        })
        .first();
      if (!own) {
        throw new Error('DeleteShiftSlot: caller is not team_manager of this team');
      }
    }

    // Refuse-if-referenced: shift_instance rows would be orphaned (FK ON DELETE CASCADE
    // would actually drop them, but D-Area-1 mandates the explicit refusal so the
    // manager doesn't silently destroy a generated schedule).
    const hasInstancesRow = await trx('shift_instance')
      .where({ shift_slot_id, tenant_id })
      .first('id');
    if (hasInstancesRow) {
      // Throw with the discriminator string the YAML toast keys on.
      throw new Error('shift_slot_has_instances');
    }

    // Audit BEFORE delete so the row's pre-image is captured in payload.
    await trx('schedule_audit').insert({
      tenant_id,
      planning_window_id: null,
      from_state: 'shift_slot_pre_delete',
      to_state: 'shift_slot_deleted',
      actor_user_id,
      actor_kind: 'user',
      payload: JSON.stringify({
        shift_slot_id,
        team_id: existing.team_id,
        pre_image: {
          name: existing.name,
          start_time: existing.start_time,
          end_time: existing.end_time,
          headcount: existing.headcount,
          required_role_tags: existing.required_role_tags,
          min_seniority: existing.min_seniority,
          display_order: existing.display_order,
        },
      }),
    });

    // DELETE — tenant_id always in WHERE per R-03-2.
    const deleteRows = await trx('shift_slot')
      .where({ id: shift_slot_id, tenant_id })
      .delete()
      .returning('id');
    if (!deleteRows || deleteRows.length === 0) {
      throw new Error('DeleteShiftSlot: shift_slot not found in tenant (post-check)');
    }

    return { shift_slot_id, team_id: existing.team_id };
  });

  return { success: true, shift_slot_id: result.shift_slot_id, team_id: result.team_id };
}

DeleteShiftSlot.schema = {
  type: 'object',
  required: ['shift_slot_id'],
  properties: {
    shift_slot_id: { type: 'string', format: 'uuid' },
  },
};
DeleteShiftSlot.connectionType = 'Knex';
DeleteShiftSlot.meta = { checkRead: false, checkWrite: false };

export default DeleteShiftSlot;
